### ISSUE TITLE
An error occurred when running the fuse.py 

### ISSUE THREAD

**Issue by d-serafly** [ethnhe/raster_triangle#11]
An error occurred when running the fuse.py , the error message is as follows:
![image](https://user-images.githubusercontent.com/75302812/145412326-30e1f889-5b8b-4073-88dc-6667cef40da6.png)
Looking forward for your reply, thank you.

**Comment by d-serafly** [comment]
File "fuse.py", line 158, unread “background_info.pkl”. Strictly follow the order of README, it can be solved.

**Comment by Jakob0330** [comment]
hello. I have the exact same error as you had before. However, I don't understand the way to solve this. I've strictly followed the instructions. Can you tell me how you solve this? Looking forward for your reply, thank you.
