### ISSUE TITLE
How much disk space does the file take up

### ISSUE THREAD

**Issue by guess-who-ami** [ethnhe/raster_triangle#12]
after this command `python3 rgbd_renderer.py --cls ape --render_num 70000`
I have generated > 100G files and haven't stopped

**Comment by guess-who-ami** [comment]
about 200G

**Comment by LEONHWH** [comment]
> about 200G

Oh god, only 'ape' for 200G?

**Comment by guess-who-ami** [comment]
> > about 200G
> 
> Oh god, only 'ape' for 200G?

yes, it is. Is anything wrong?

**Comment by LEONHWH** [comment]
> > > about 200G
> > 
> > 
> > Oh god, only 'ape' for 200G?
> 
> yes, it is. Is anything wrong?

I mean if I'm going to train pvn3d or FFB6D, whether I have to execute the code `python3 fuse.py --cls & python3 rgbd_renderer.py --cls` per object? In that case, to train 13 objects in the entire linemod dataset, I may have to prepare 13*200G of memory space....

**Comment by guess-who-ami** [comment]
> 

you can generate one object dataset, and train the model for the object. Then generate the next dataset. In that way, you can only use 200G memory space.

**Comment by ethnhe** [comment]
There are several ways to save memory space:
1. Randomly sample the pose and generate less than 70000 scenes. I think about 10000 scenes are enough to get a good performance.
2. Save the generated RGB images to ".jpg", segmentation mask to ".png" using cv2.imwrite; convert the depth image to be in mm and uint16 data type and save it to ".png" using [pypng](https://pypng.readthedocs.io/en/latest/ex.html#writing); save the remaining info dictionary to pickle. That will save a lot of space compared to the full-pickle version as it has compression. I think it will take about 10G for the full 70000 scenes in this way.
