### ISSUE TITLE
No error message, no pose pkl files generated

### ISSUE THREAD

**Issue by MiriamJo** [ethnhe/raster_triangle#18]
I am confused on how the rgbd_renderer.py will not throw any errors, but won't render my rgb, mask and depth images corectly. With all of the LineMOD Example Meshes it does in fact create the data, and also visualises it with the --vis tag.
However, when I try to apply it to my own data, nothing happens. I prepared my data in a LineMod Style, wirh all of the folders and required information.

**Provided Structure for my new class:**
- data/cls_number/depth folder (empty)
- data/cls_number/mask folder (empty)
- data/cls_number/rgb folder (empty)
- gt.yml & info.yml (empty)
- text.txt , train.txt (empty)
- data/models/obj_classnumber.ply (vertex colored ply model)
- data/sampled_poses/myclass_sampled_RTs.pkl (some npy array of another object, duplicated and renamed, since i don't know how to use the npy array created in the pvnet-rendering)

When I run the script with 
`python3 rgbd_renderer.py --cls myclass --render_num 1 --vis`

it does come up with the usual output:
`cls: myclass`
`begin loading myclass render set:`
`lit [00:00, 20.69it/s]`

But nothing happens. It does not create a folder in the renders folder or writes any other data.
What am I missing?

**Comment by MiriamJo** [comment]
Update: The "file_list.txt" is being created, but without any content. it's just an empty txt file.

**Comment by MiriamJo** [comment]
Alright. I fixed the problem by generating Data with BlenderProc. It gives me all of the Data I need to complete the linemod mock data. After that, all of the files were generated completely. It would be really appreciated to add some more information for working with a custom dataset.

**Comment by jasmine202106** [comment]
Hi, i met the same question with you, but i generated the custom dataset with ObjectDatasetTools. Could you please give me some help for the problem? thanks.
