### ISSUE TITLE
New Object

### ISSUE THREAD

**Issue by Michael187-ctrl** [ethnhe/raster_triangle#3]
Hey, thanks for sharing this great work.

Can someone tell me, how to create pictures for a new object?
Greetings Michael

**Comment by ethnhe** [comment]
One workaround way is to modify the path to your ply path [here](https://github.com/ethnhe/raster_triangle/blob/fb3c0ebfe6101deeed6dcd7fa9779976b2ae0021/rgbd_renderer.py#L92). But the unit of vertexes in the ply model should be in meter. The color of each vertex also should be in the ply or the rendered RGB image may be wrong. The raster triangle doesn't support models using the uv map yet.

**Comment by Y-pandaman** [comment]
您好，我有个obj模型文件，以及对应的mtl文件，请问怎么转换成ply文件，我用meshlab和cloudcompare直接转成ply文件，加载时会报错缺少颜色信息
