### ISSUE TITLE
sampled poses

### ISSUE THREAD

**Issue by Michael187-ctrl** [ethnhe/raster_triangle#4]
Can you please explain, how you get the sampled_poses with https://github.com/zju3dv/pvnet-rendering ?  I want to use it for my own objects.
Best regards Michael

**Comment by Michael187-ctrl** [comment]
Can someone please help me and tell me how https://github.com/zju3dv/pvnet-rendering is used for getting the sampled poses and how I could use it for my own Dataset?
Would really appreciate your help. 
Greetings Michael

**Comment by ethnhe** [comment]
After you setup [pvnet-rendering](https://github.com/zju3dv/pvnet-rendering) and run
```
python run.py --type rendering
```
There will be a folder that contains the generated poses. Each file with one sampled pose.
We set the number of sampled poses to be 70000 before running and collect them to a single file.
For your own dataset, I think using our sampled pose is enough.

**Comment by hz-ants** [comment]
Dear author,
pvnet-rendering generates an npy file.I want to know how to convert the .npy file into the required sampled_RTs.pkl? I use import pickle to see that array is different. Thank you

**Comment by MiriamJo** [comment]
Can you explain on how it works using the pre-generated files? Is it not depending on the object? Why bother creating so much files when one can use them for any object?
