### ISSUE TITLE
Typo in your code & Download link for SUN2012 invalid

### ISSUE THREAD

**Issue by CandiceD17** [ethnhe/raster_triangle#7]
Hii there
When I run your script rgbd_renderer.py, I received an error saying:

File "rgbd_renderer.py", line 173, in gen_pack_zbuf_render
    bg_pth = args.bg_img_pth_lst[randint(0, len_bg_lst-1)]
AttributeError: 'Namespace' object has no attribute 'bg_img_pth_lst'

I think the `args.bg_img_pth_lst` should be `self.bg_img_pth_lst`.

For the download link, I tried: https://github.com/ShapeNet/RenderForCNN/blob/master/datasets/get_sun2012pascalformat.sh and it works for me.

Overall, I really appreciate your work and thank you for all of it!!

**Comment by ethnhe** [comment]
Thanks for the suggestion.
- The typo is fixed. 
- The link to sun_rgbd is added. The original one works well with firefox or right-click and open the link in the new tab in chome, not sure why not work with a direct click.
