### ISSUE TITLE
An error occurred when running the rgbd_render.py 

### ISSUE THREAD

**Issue by peppa114** [ethnhe/raster_triangle#8]
An error occurred when running the rgbd_renderer.py , the error message is as follows:
![Screenshot from 2021-05-20 15-17-34](https://user-images.githubusercontent.com/83171253/118936333-09b87200-b97f-11eb-9832-f287807a67c8.png)
I need the processing results of Linemod set to be used in FFB6D. Looking forward for your reply, thank you.

**Comment by liupenglei** [comment]
> An error occurred when running the rgbd_renderer.py , the error message is as follows:
> ![Screenshot from 2021-05-20 15-17-34](https://user-images.githubusercontent.com/83171253/118936333-09b87200-b97f-11eb-9832-f287807a67c8.png)
> I need the processing results of Linemod set to be used in FFB6D. Looking forward for your reply, thank you.

Have you solved it ? I meet the same problem. Thank you .

**Comment by ethnhe** [comment]
It seems that the length of self.bg_img_pth_lst is 0, maybe the path to the background image, the SUN2012pascalformat dataset is not set properly. Follow the README instruction:
Download SUN2012pascalformat dataset from herehttp://groups.csail.mit.edu/vision/SUN/releases/SUN2012pascalformat.tar.gz. Unzip it and link the unzipped folder to this folder:
```
ln -s path_to_SUN2012pascalformat ./
```

**Comment by Gauravajariwal11** [comment]
hi @ethnhe 

But the SUN2012 is a different dataset than LineMod right? So, while implementing[this step](https://github.com/ethnhe/FFB6D#:~:text=Generate%20rendered%20and%20fused%20data%20following%20raster_triangle.) , we need to generate rendered data using rgbd_renderer.py on LineMod dataset... and that gives an error.

**Comment by ethnhe** [comment]
Yes, SUN2012 is an RGB-only dataset for background generation. We randomly sample an image from SUN2012 and paste the foreground to that background. The related code is [here](https://github.com/ethnhe/raster_triangle/blob/c4555ac09a9d36d855e9cf05ff7535b5e764696c/rgbd_renderer.py#L170) from Line 170 to 197.

**Comment by Gauravajariwal11** [comment]
I got the idea of randomly sampling an image from SUN2012. But I get the same issue when I do it for Linemod dataset.

What I have done as of now is soft linked the dataset by ln -s path_to_linemod_dataset  ffb6d/dataset/linemod/

What am I doing wrong here? any ideas? I am trying to train ffb6d model, but first I need raster_trianle script to render data, right?

**Comment by ethnhe** [comment]
Follow the [README](https://github.com/ethnhe/raster_triangle#datasets) in this repo to set up and generate synthesis data

**Comment by Gauravajariwal11** [comment]
Sorry to disturb you again. I did exactly as the README suggested but the Linemod dataset and rgbd_renderer file are giving me this error mentioned above:

![Screenshot from 2021-08-31 01-37-08](https://user-images.githubusercontent.com/28729137/131454167-4d2ac161-d5af-41a2-b7c6-71dc6a68fb92.png)

the fuse.py works fine, but not the rgbd_renderer. Any suggestions?
