### ISSUE TITLE
[Errno 2] No such file or directory: 'sampled_poses/ape_sampled_RTs.pkl'

### ISSUE THREAD

**Issue by liupenglei** [ethnhe/raster_triangle#9]
Hello,
Thank you for your work, but I have a problem. When I run “python3 rgbd_renderer.py --cls ape --render_num 70000”, an error occurs

[Errno 2] No such file or directory: 'sampled_poses/ape_sampled_RTs.pkl'

Thank you in advance!

**Comment by yangshunDragon** [comment]
@ethnhe   Hello, ethnhe. Sorry for bothering you. If I have a new class which I name it as "bookcase".    What should I do genetate my "sampled_poses/bookcase_sampled_RTs.pkl"?
